name: PR duplicate check
on: [push, pull_request_target]
jobs:
  duplicate_check:
    name: Check for duplicates
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Check for duplicates
        run: |
          duplicates=$(sort config.yaml | grep -v "excludeRepos\|includeRepos" | uniq -cd)
          line_count=$(echo "$duplicates" | wc -l)
          if [ $line_count -ne 1 ]; then
            echo "Duplicates found: $duplicates"
            exit 1 
          fi
